<?php

namespace ContainerYzeBZ3t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllersearchByTelephoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..XbHHm9.App\Controller\ClientController::searchByTelephone()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..XbHHm9.App\\Controller\\ClientController::searchByTelephone()'] = ($container->privates['.service_locator..XbHHm9'] ?? $container->load('get_ServiceLocator__XbHHm9Service'))->withContext('App\\Controller\\ClientController::searchByTelephone()', $container);
    }
}
