<?php

namespace ContainerD9TXMbV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X1fCxrZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x1fCxrZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x1fCxrZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.IqSceiR.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator..XbHHm9.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::create()', 'getClientControllercreateService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController::showByEtat' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::showByEtat()', 'getClientControllershowByEtatService', true],
            'App\\Controller\\DetteController::index' => ['privates', '.service_locator.AjxBq8..App\\Controller\\DetteController::index()', 'getDetteControllerindexService', true],
            'App\\Controller\\DetteController::create' => ['privates', '.service_locator.dhQeSJ7.App\\Controller\\DetteController::create()', 'getDetteControllercreateService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.OgKtQNk.App\\Controller\\UsersController::index()', 'getUsersControllerindexService', true],
            'App\\Controller\\UsersController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UsersController::create()', 'getUsersControllercreateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.IqSceiR.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator..XbHHm9.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::create()', 'getClientControllercreateService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController:showByEtat' => ['privates', '.service_locator.bSaFovV.App\\Controller\\ClientController::showByEtat()', 'getClientControllershowByEtatService', true],
            'App\\Controller\\DetteController:index' => ['privates', '.service_locator.AjxBq8..App\\Controller\\DetteController::index()', 'getDetteControllerindexService', true],
            'App\\Controller\\DetteController:create' => ['privates', '.service_locator.dhQeSJ7.App\\Controller\\DetteController::create()', 'getDetteControllercreateService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.OgKtQNk.App\\Controller\\UsersController::index()', 'getUsersControllerindexService', true],
            'App\\Controller\\UsersController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\UsersController::create()', 'getUsersControllercreateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::create' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\ClientController::showByEtat' => '?',
            'App\\Controller\\DetteController::index' => '?',
            'App\\Controller\\DetteController::create' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Controller\\UsersController::create' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:create' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\ClientController:showByEtat' => '?',
            'App\\Controller\\DetteController:index' => '?',
            'App\\Controller\\DetteController:create' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'App\\Controller\\UsersController:create' => '?',
        ]);
    }
}
