<?php

namespace ContainerD9TXMbV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllershowByEtatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bSaFovV.App\Controller\ClientController::showByEtat()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bSaFovV.App\\Controller\\ClientController::showByEtat()'] = ($container->privates['.service_locator.bSaFovV'] ?? $container->load('get_ServiceLocator_BSaFovVService'))->withContext('App\\Controller\\ClientController::showByEtat()', $container);
    }
}
