<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG9hdRxR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG9hdRxR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG9hdRxR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG9hdRxR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG9hdRxR\App_KernelDevDebugContainer([
    'container.build_hash' => 'G9hdRxR',
    'container.build_id' => '8f21aab3',
    'container.build_time' => 1728604350,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG9hdRxR');
