<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzeBZ3t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzeBZ3t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYzeBZ3t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYzeBZ3t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYzeBZ3t\App_KernelDevDebugContainer([
    'container.build_hash' => 'YzeBZ3t',
    'container.build_id' => '7e73a613',
    'container.build_time' => 1729029572,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzeBZ3t');
