<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_flowbite_lib_esm_index_js-node_modules_core-js_modules_es_date_to-primit-b229d2.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_flowbite_dist_flowbite_min_css.css',
                '/build/app.css',
            ],
        ],
        'styles' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/vendors-node_modules_flowbite_dist_flowbite_min_css.css',
                '/build/styles.css',
            ],
        ],
        'scripJs' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_flowbite_lib_esm_index_js-node_modules_core-js_modules_es_date_to-primit-b229d2.js',
            ],
            'css' => [
                '/build/vendors-node_modules_flowbite_dist_flowbite_min_css.css',
                '/build/scripJs.css',
            ],
        ],
    ],
],

]];
